### ISSUE TITLE
ImportError: No module named tkinter

### ISSUE THREAD

**Issue by ayrtondutchman** [CMDR-Kiel42/EDMC_SpanshRouter#25]
Hi there!

Today I tried to install EDMC_SpanshRouter on my EDMC install. And it didn't load. 
So I know that some plugins required python 3.7 so I went from python 3.6 to 3.7 but it didn't fix it.
When I looked into the log file it said something about not being able to import tkinter while tkinter is included by default in python installs.

Full error:
> `loading plugin EDMC_SpanshRouter from "C:\Users\...\AppData\Local\EDMarketConnector\plugins\EDMC_SpanshRouter\load.py"
Traceback (most recent call last):
  File "plug.pyo", line 193, in load_plugins
  File "plug.pyo", line 94, in __init__
  File "C:\Users\...\AppData\Local\EDMarketConnector\plugins\EDMC_SpanshRouter\load.py", line 2, in <module>
  File "C:\Users\...\AppData\Local\EDMarketConnector\plugins\EDMC_SpanshRouter\SpanshRouter\__init__.py", line 3, in <module>
  File "C:\Users\...\AppData\Local\EDMarketConnector\plugins\EDMC_SpanshRouter\SpanshRouter\SpanshRouter.py", line 13, in <module>
  File "C:\Users\...\AppData\Local\EDMarketConnector\plugins\EDMC_SpanshRouter\SpanshRouter\AutoCompleter.py", line 8, in <module>
ImportError: No module named tkinter`

I don't know if this is an issue on my side or just in general but any help would be appreciated.
My thanks in advance.

**Comment by CMDR-Kiel42** [comment]
This is odd, I can't reproduce with the latest version of EDMC... You are running the latest one (4.1.4), right?

**Comment by ayrtondutchman** [comment]
Found the issue, I was indeed running an older (actually too old version) of EDMC which was still running python 2.7. Now upgraded to the newest version and it seems to be working. The EDMC updater was crashing on me constantly so that was a little troubling but it seems to be working now.
